version: "3.8"

services:
  qr-system-rust:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-system-rust:latest
    container_name: qr-system-rust-container
    restart: unless-stopped
    ports:
      - "8080:8080" 
    volumes:
      - .:/usr/src/qr-system-rust 
